## https://help.sonatype.com/en/installation-methods.html
## https://help.sonatype.com/en/installation-methods.html#installing-with-docker

## https://github.com/sonatype/docker-nexus3/blob/main/Dockerfile
## https://hub.docker.com/r/sonatype/nexus3/tags
## https://help.sonatype.com/en/installation-methods.html

services:
  nexus:
    image: sonatype/nexus3
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}
