## https://docs.sonarsource.com/sonarqube/latest/
## https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/installation-requirements/overview/
## https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/installation-requirements/server-host/
## https://docs.sonarsource.com/sonarqube/10.4/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/

# Source: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
services:
  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
        # - sonarqube_data:/opt/sonarqube/data
        # - sonarqube_extensions:/opt/sonarqube/extensions
        # - sonarqube_logs:/opt/sonarqube/logs
        # - sonarqube_temp:/opt/sonarqube/temp
      - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/data:/opt/sonarqube/data
      - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/extensions:/opt/sonarqube/extensions
      - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/logs:/opt/sonarqube/logs
      - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/temp:/opt/sonarqube/temp
    ports:
      - "9000:9000"
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_temp:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: