## https://docs.sonarsource.com/sonarqube/latest/
## https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/installation-requirements/overview/
## https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/installation-requirements/server-host/
## https://docs.sonarsource.com/sonarqube/10.4/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/

## Requirements: https://docs.sonarsource.com/sonarqube/9.9/requirements/prerequisites-and-overview/

# Source: https://github.com/SonarSource/docker-sonarqube/blob/master/example-compose-files/sq-with-postgres/docker-compose.yml
services:
  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: sonarqube
    read_only: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: /run/secrets/db_jdbc_url
        # SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: /run/secrets/db_sonar_user
      SONAR_JDBC_PASSWORD: /run/secrets/db_sonar_password
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
        # - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/data:/opt/sonarqube/data
        # - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/extensions:/opt/sonarqube/extensions
        # - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/logs:/opt/sonarqube/logs
        # - /Volumes/fot-sandisk-4TB/IT/Disks/nexus/temp:/opt/sonarqube/temp
    ports:
      - "9000:9000"

secrets:
   db_jdbc_url:
     file: db_jdbc_url.txt
   db_sonar_user:
     file: db_sonar_user.txt
   db_sonar_password:
     file: db_sonar_password.txt

volumes:
  sonarqube_data:
  sonarqube_temp:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: