services:   ## https://hub.docker.com/_/postgres
  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/vagrant/postgresql-data:/var/lib/postgresql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"

 # secrets:
 #    db_password:
 #      file: db_password.txt
 #    db_root_password:
 #      file: db_root_password.txt

  # volumes:
  #   - postgresql:/var/lib/postgresql
  #   - postgresql_data:/var/lib/postgresql/data